module: Daydream
author: Sachin Patel
author_url: https://gizmosachin.com
github_url: https://github.com/gizmosachin/Daydream
readme: ./source/README.md
xcodebuild-arguments: -scheme,Daydream
exclude: []
copyright: '© 2017 [Sachin Patel](http://gizmosachin.com).'
swift_version: 3.0
exclude: ./source/Sources/DDControllerState.swift
