language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - brew reinstall xctool
script:
  - xcodebuild -showsdks
  - xcodebuild -project Daydream/Daydream.xcodeproj -scheme Daydream -sdk iphonesimulator10.0 build analyze

